Remove pytest-runner from setup-requires to fix setup.py on Windows:
It seems that easy install can't install pytest-runner on Windows:

distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')